"""Add orders table

Revision ID: 1eb22cd7bf56
Revises: b241f21bd0f8
Create Date: 2025-04-01 15:54:16.231936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1eb22cd7bf56"
down_revision: Union[str, None] = "b241f21bd0f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("is_full_shipment", sa.Boolean(), nullable=True))
    op.add_column(
        "machinery", sa.Column("old_id", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "orders", sa.Column("old_id", sa.String(), nullable=False, server_default="")
    )
    op.drop_constraint(None, "orders_items", type_="foreignkey")
    op.create_foreign_key(None, "orders_items", "orders", ["order_id"], ["id"])
    op.add_column("shipments", sa.Column("photos", sa.JSON(), nullable=False))
    # ### end Alembic commands ###

    # Set default value for existing rows in machinery.old_id
    op.execute("UPDATE machinery SET old_id = ''")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipments", "photos")
    op.drop_constraint(None, "orders_items", type_="foreignkey")
    op.create_foreign_key(None, "orders_items", "machinery", ["order_id"], ["id"])
    op.drop_column("orders", "old_id")
    op.drop_column("machinery", "old_id")
    op.drop_column("invoice", "is_full_shipment")
    # ### end Alembic commands ###
