"""Reinitialize database_3

Revision ID: 7458d59810ba
Revises: 
Create Date: 2025-04-03 13:16:58.089708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7458d59810ba"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoice", "shipment_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("shipment_id", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
