"""Reinitialize database

Revision ID: ebe153db5116
Revises: 
Create Date: 2025-04-01 17:53:37.596431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = "ebe153db5116"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    if "machinery" not in inspector.get_table_names():
        op.create_table(
            "machinery",
            sa.Column("old_id", sa.String(), nullable=False),
            sa.Column("brand", sa.String(length=32), nullable=False),
            sa.Column("model", sa.String(length=32), nullable=False),
            sa.Column("year_manufacture", sa.Integer(), nullable=False),
            sa.Column("type_id", sa.Integer(), nullable=False),
            sa.Column("vin", sa.String(length=32), nullable=False),
            sa.Column("state_number", sa.String(length=32), nullable=True),
            sa.Column("status", sa.String(length=32), nullable=True),
            sa.Column("photos", sa.JSON(), nullable=False),
            sa.Column("traction_type_id", sa.Integer(), nullable=True),
            sa.Column("engine_type_id", sa.Integer(), nullable=True),
            sa.Column("operating_type_id", sa.Integer(), nullable=True),
            sa.Column("transmission_type_id", sa.Integer(), nullable=True),
            sa.Column("working_equipment", sa.String(length=32), nullable=True),
            sa.Column("engine_brand", sa.String(length=32), nullable=True),
            sa.Column("engine_model", sa.String(length=32), nullable=True),
            sa.Column("transmission_brand", sa.String(length=32), nullable=True),
            sa.Column("transmission_model", sa.String(length=32), nullable=True),
            sa.Column("frame_number", sa.String(length=32), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    if "shipments" not in inspector.get_table_names():
        op.create_table(
            "shipments",
            sa.Column("old_id", sa.String(length=100), nullable=False),
            sa.Column("author_id", sa.Integer(), nullable=True),
            sa.Column("is_received", sa.Boolean(), nullable=False),
            sa.Column("received_author_id", sa.Integer(), nullable=True),
            sa.Column("received_date", sa.Integer(), nullable=True),
            sa.Column("lading_number", sa.String(), nullable=False),
            sa.Column("lading_file_path", sa.String(), nullable=False),
            sa.Column("transporter", sa.String(), nullable=False),
            sa.Column("type", sa.String(), nullable=False),
            sa.Column("photos", sa.JSON(), nullable=False),
            sa.Column("invoices_id", sa.JSON(), nullable=False),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    if "subscribers" not in inspector.get_table_names():
        op.create_table(
            "subscribers",
            sa.Column("chat_id", sa.Integer(), nullable=True),
            sa.Column("username", sa.String(), nullable=True),
            sa.Column("is_active", sa.Boolean(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("chat_id"),
        )
    if "suppliers" not in inspector.get_table_names():
        op.create_table(
            "suppliers",
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("INN", sa.Integer(), nullable=True),
            sa.Column("old_id", sa.String(length=100), nullable=False),
            sa.Column("city", sa.String(length=32), nullable=False),
            sa.Column("phone", sa.String(length=32), nullable=False),
            sa.Column("manager_email", sa.String(length=64), nullable=False),
            sa.Column(
                "accounts_department_email", sa.String(length=64), nullable=False
            ),
            sa.Column("kpp", sa.Integer(), nullable=True),
            sa.Column("Legal_address", sa.String(length=600), nullable=False),
            sa.Column("bik", sa.Integer(), nullable=True),
            sa.Column("correspondent_account", sa.Integer(), nullable=True),
            sa.Column("payment_account", sa.Integer(), nullable=True),
            sa.Column("bank", sa.String(length=600), nullable=False),
            sa.Column("ogrn", sa.Integer(), nullable=True),
            sa.Column("okpo", sa.Integer(), nullable=True),
            sa.Column("okato", sa.Integer(), nullable=True),
            sa.Column("okogu", sa.Integer(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    if "users" not in inspector.get_table_names():
        op.create_table(
            "users",
            sa.Column("first_name", sa.String(length=32), nullable=False),
            sa.Column("middle_name", sa.String(length=32), nullable=False),
            sa.Column("email", sa.String(length=32), nullable=False),
            sa.Column("role_id", sa.Integer(), nullable=False),
            sa.Column("password", sa.String(length=128), nullable=False),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("email"),
        )
    if "invoice" not in inspector.get_table_names():
        op.create_table(
            "invoice",
            sa.Column("old_id", sa.String(length=100), nullable=False),
            sa.Column("author_id", sa.Integer(), nullable=True),
            sa.Column("is_approved", sa.Boolean(), nullable=False),
            sa.Column("approved_author_id", sa.Integer(), nullable=True),
            sa.Column("approved_date", sa.Integer(), nullable=True),
            sa.Column("is_paid", sa.Boolean(), nullable=False),
            sa.Column("paid_author_id", sa.Integer(), nullable=True),
            sa.Column("paid_date", sa.Integer(), nullable=True),
            sa.Column("payment_order_patch", sa.String(length=100), nullable=False),
            sa.Column("number", sa.String(length=1024), nullable=False),
            sa.Column("amount", sa.Integer(), nullable=False),
            sa.Column("is_with_vat", sa.Boolean(), nullable=False),
            sa.Column("request_id", sa.Integer(), nullable=True),
            sa.Column("shipment_id", sa.Integer(), nullable=True),
            sa.Column("is_full_shipment", sa.Boolean(), nullable=True),
            sa.Column("invoice_patch", sa.String(length=1024), nullable=False),
            sa.Column("is_cancel", sa.Boolean(), nullable=False),
            sa.Column("cancel_date", sa.Integer(), nullable=True),
            sa.Column("cancel_author_id", sa.Integer(), nullable=True),
            sa.Column("supplier_id", sa.Integer(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.ForeignKeyConstraint(
                ["supplier_id"],
                ["suppliers.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if "machinery_comment" not in inspector.get_table_names():
        op.create_table(
            "machinery_comment",
            sa.Column("text", sa.String(length=400), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column("author_id", sa.Integer(), nullable=False),
            sa.Column("rating", sa.JSON(), nullable=False),
            sa.Column("machinery_id", sa.Integer(), nullable=False),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.ForeignKeyConstraint(
                ["machinery_id"],
                ["machinery.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if "machinery_docs" not in inspector.get_table_names():
        op.create_table(
            "machinery_docs",
            sa.Column("title", sa.String(length=32), nullable=False),
            sa.Column("file_name", sa.String(length=400), nullable=False),
            sa.Column("machinery_id", sa.Integer(), nullable=False),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.ForeignKeyConstraint(
                ["machinery_id"],
                ["machinery.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if "machinery_problem" not in inspector.get_table_names():
        op.create_table(
            "machinery_problem",
            sa.Column("title", sa.String(length=128), nullable=False),
            sa.Column("description", sa.String(length=1024), nullable=False),
            sa.Column("priority_id", sa.Integer(), nullable=False),
            sa.Column("photos", sa.JSON(), nullable=False),
            sa.Column("author_id", sa.Integer(), nullable=False),
            sa.Column("category_id", sa.Integer(), nullable=False),
            sa.Column("status_id", sa.Integer(), nullable=False),
            sa.Column("operating", sa.Integer(), nullable=True),
            sa.Column("odometer", sa.Integer(), nullable=True),
            sa.Column("machinery_id", sa.Integer(), nullable=True),
            sa.Column("tasks_id", sa.JSON(), nullable=False),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.ForeignKeyConstraint(
                ["machinery_id"],
                ["machinery.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if "orders" not in inspector.get_table_names():
        op.create_table(
            "orders",
            sa.Column("old_id", sa.String(), nullable=False),
            sa.Column("author_id", sa.Integer(), nullable=True),
            sa.Column("title", sa.String(), nullable=False),
            sa.Column("is_approved", sa.Boolean(), nullable=False),
            sa.Column("approved_author_id", sa.Integer(), nullable=True),
            sa.Column("approved_date", sa.Integer(), nullable=True),
            sa.Column("assigned_to_id", sa.Integer(), nullable=True),
            sa.Column("shipment_type", sa.String(), nullable=False),
            sa.Column("order_type", sa.String(), nullable=False),
            sa.Column("comment", sa.String(), nullable=False),
            sa.Column("machinery_id", sa.Integer(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.ForeignKeyConstraint(
                ["machinery_id"],
                ["machinery.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if "machinery_tasks" not in inspector.get_table_names():
        op.create_table(
            "machinery_tasks",
            sa.Column("title", sa.String(length=128), nullable=False),
            sa.Column("description", sa.String(length=1024), nullable=False),
            sa.Column("event_location", sa.String(length=1024), nullable=False),
            sa.Column("type_id", sa.Integer(), nullable=False),
            sa.Column("status_id", sa.Integer(), nullable=False),
            sa.Column("priority_id", sa.Integer(), nullable=False),
            sa.Column("due_date", sa.Integer(), nullable=False),
            sa.Column("issue_operating", sa.Integer(), nullable=True),
            sa.Column("issue_odometer", sa.Integer(), nullable=True),
            sa.Column("issue_photos", sa.JSON(), nullable=False),
            sa.Column("result_photos", sa.JSON(), nullable=False),
            sa.Column("result_description", sa.String(length=1024), nullable=False),
            sa.Column("result_operating", sa.Integer(), nullable=True),
            sa.Column("result_odometer", sa.Integer(), nullable=True),
            sa.Column("spent_resources", sa.String(length=1024), nullable=False),
            sa.Column("author_id", sa.Integer(), nullable=False),
            sa.Column("assigned_to_id", sa.Integer(), nullable=False),
            sa.Column("machinery_id", sa.Integer(), nullable=True),
            sa.Column("problem_id", sa.Integer(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.ForeignKeyConstraint(
                ["machinery_id"],
                ["machinery.id"],
            ),
            sa.ForeignKeyConstraint(
                ["problem_id"],
                ["machinery_problem.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if "orders_items" not in inspector.get_table_names():
        op.create_table(
            "orders_items",
            sa.Column("name", sa.String(), nullable=False),
            sa.Column("catalogNumber", sa.String(), nullable=False),
            sa.Column("count", sa.Integer(), nullable=False),
            sa.Column("comment", sa.String(), nullable=False),
            sa.Column("is_ordered", sa.Boolean(), nullable=False),
            sa.Column("completionType", sa.String(), nullable=False),
            sa.Column("photos", sa.JSON(), nullable=False),
            sa.Column("invoice_id", sa.Integer(), nullable=True),
            sa.Column("order_id", sa.Integer(), nullable=True),
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("created_date", sa.BigInteger(), nullable=False),
            sa.Column("updated_date", sa.BigInteger(), nullable=False),
            sa.ForeignKeyConstraint(
                ["invoice_id"],
                ["invoice.id"],
            ),
            sa.ForeignKeyConstraint(
                ["order_id"],
                ["orders.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
        )
    if "shipments_invoices" not in inspector.get_table_names():
        op.create_table(
            "shipments_invoices",
            sa.Column("shipment_id", sa.Integer(), nullable=False),
            sa.Column("invoice_id", sa.Integer(), nullable=False),
            sa.Column("orders_item_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["invoice_id"],
                ["invoice.id"],
            ),
            sa.ForeignKeyConstraint(
                ["orders_item_id"],
                ["orders_items.id"],
            ),
            sa.ForeignKeyConstraint(
                ["shipment_id"],
                ["shipments.id"],
            ),
            sa.PrimaryKeyConstraint("shipment_id", "invoice_id"),
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipments_invoices")
    op.drop_table("orders_items")
    op.drop_table("machinery_tasks")
    op.drop_table("orders")
    op.drop_table("machinery_problem")
    op.drop_table("machinery_docs")
    op.drop_table("machinery_comment")
    op.drop_table("invoice")
    op.drop_table("users")
    op.drop_table("suppliers")
    op.drop_table("subscribers")
    op.drop_table("shipments")
    op.drop_table("machinery")
    # ### end Alembic commands ###
