"""added type_id to problem_6

Revision ID: ad8ed78c5bb9
Revises: c0dd5daf8425
Create Date: 2025-03-03 15:59:35.476507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad8ed78c5bb9"
down_revision: Union[str, None] = "c0dd5daf8425"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("machinery_tasks", sa.Column("type_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("machinery_tasks", "type_id")
    # ### end Alembic commands ###
