"""Reinitialize database

Revision ID: e200eb6caf82
Revises: 
Create Date: 2025-04-01 17:42:28.614738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e200eb6caf82"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders_items", type_="foreignkey")
    op.create_foreign_key(None, "orders_items", "orders", ["order_id"], ["id"])

    # Добавляем server_default для существующих данных
    op.add_column(
        "shipments_invoices",
        sa.Column(
            "orders_item_id",
            sa.Integer(),
            nullable=False,
            server_default="0",  # Или используйте значение по умолчанию, которое подходит
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shipments_invoices", type_="foreignkey")
    op.drop_column("shipments_invoices", "orders_item_id")
    op.drop_constraint(None, "orders_items", type_="foreignkey")
    op.create_foreign_key(None, "orders_items", "machinery", ["order_id"], ["id"])
    # ### end Alembic commands ###
