"""added type_id to problem_8

Revision ID: 86ddfc6c78ab
Revises: e831d2f79c2c
Create Date: 2025-03-10 12:19:40.916978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86ddfc6c78ab"
down_revision: Union[str, None] = "e831d2f79c2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
