"""add frame_number to machinery

Revision ID: 9bf3f708cb69
Revises: 895fb3a09b80
Create Date: 2025-02-25 21:10:36.931605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bf3f708cb69"
down_revision: Union[str, None] = "895fb3a09b80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "machinery", sa.Column("operating_type_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "machinery", sa.Column("frame_number", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("machinery", "frame_number")
    op.drop_column("machinery", "operating_type_id")
    # ### end Alembic commands ###
