"""Add suppliers table

Revision ID: b241f21bd0f8
Revises: 0cd2cc0e0e2d
Create Date: 2025-03-29 16:49:31.391291

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b241f21bd0f8"
down_revision: Union[str, None] = "0cd2cc0e0e2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
