"""added event location to task 2

Revision ID: 0cd2cc0e0e2d
Revises: 7f0acd1af5f7
Create Date: 2025-03-29 13:12:04.410587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cd2cc0e0e2d"
down_revision: Union[str, None] = "7f0acd1af5f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
