"""added subscribe table_3

Revision ID: 6db16ccc3c6d
Revises: 5ea6dcb60876
Create Date: 2025-02-01 17:18:45.014861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6db16ccc3c6d"
down_revision: Union[str, None] = "5ea6dcb60876"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscribers", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscribers", "is_active")
    # ### end Alembic commands ###
