"""added tasks_views_3

Revision ID: 3a46a93baa6b
Revises: 
Create Date: 2025-01-22 20:12:01.854094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a46a93baa6b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machinery",
        sa.Column("brand", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("year_manufacture", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("vin", sa.String(length=32), nullable=False),
        sa.Column("state_number", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("photos", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.BigInteger(), nullable=False),
        sa.Column("updated_date", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=32), nullable=False),
        sa.Column("middle_name", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=32), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.BigInteger(), nullable=False),
        sa.Column("updated_date", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "machinery_comment",
        sa.Column("text", sa.String(length=400), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.JSON(), nullable=False),
        sa.Column("machinery_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.BigInteger(), nullable=False),
        sa.Column("updated_date", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machinery_id"],
            ["machinery.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "machinery_docs",
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column("file_name", sa.String(length=400), nullable=False),
        sa.Column("machinery_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.BigInteger(), nullable=False),
        sa.Column("updated_date", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machinery_id"],
            ["machinery.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("priority_id", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Integer(), nullable=False),
        sa.Column("issue_photos", sa.JSON(), nullable=False),
        sa.Column("result_photos", sa.JSON(), nullable=False),
        sa.Column("result_description", sa.String(length=1024), nullable=False),
        sa.Column("spent_resources", sa.String(length=1024), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), nullable=False),
        sa.Column("machinery_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.BigInteger(), nullable=False),
        sa.Column("updated_date", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machinery_id"],
            ["machinery.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("machinery_docs")
    op.drop_table("machinery_comment")
    op.drop_table("users")
    op.drop_table("machinery")
    # ### end Alembic commands ###
